version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app:ro
    working_dir: /usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
